export const MyClients = [
    {
        name: "Kenneth Ocitti",
        mobile: "0784120151",
        bussiness: "Construction",
        id: 1,
        role: "Admin",
        date: '01-12-2021',
        status:"",
        enteredBy: "Kenny",
        role: "Admin",
        amount: "44000",
        desc: "descriptions",
    },
    {
        name: "Acen Juliet",
        mobile: "0784167899",
        bussiness: "Hard ware",
        id: 2,
        date: '09-08-2021',
        enteredBy: "Kenny",
        status:"New",
        role: "Field Boy",
        amount: "44000",
        desc: "descriptions",
    },
    {
        name: "Akello Gloria",
        mobile: "0771003388",
        bussiness: "Electronics",
        desc: "descriptions",
        id: 3,
        date: '03-09-2021',
        enteredBy: "Kenny",
        status:"",
        role: "Admin",
        amount: "44000"
    },
    {
        desc: "descriptions",
        name: "Okello Bosco",
        mobile: "0784890248",
        bussiness: "Driving",
        id: 4,
        date: '5-10-2021',
        enteredBy: "Kenny",
        status:"New",
        role: "Admin",
        amount: "44000"
    },
    {
        name: "Walter Nyeko",
        desc: "descriptions",
        mobile: "0784120151",
        bussiness: "Farmer",
        id: 5,
        date: '09-08-2021',
        enteredBy: "Kenny",
        role: "Field Boy",
        amount: "44000",
        status:"New",
    },

    {
        name: "Sunday Odong",
        mobile: "0784120151",
        bussiness: "Java Dev",
        bussiness: "Construction",
        status:"",
        id: 6,
        date: '09-08-2021',
        desc: "descriptions",
        enteredBy: "Kenny",
        role: "Admin",
        amount: "44000"
    }, {
        name: "Buzic Okeca",
        mobile: "0784120151",
        bussiness: "Pesticides",
        status:"New",
        date: '09-08-2021',
        desc: "descriptions",
        id: 7,
        date: '09-08-2021',
        enteredBy: "Kenny",
        role: "Admin",
        amount: "44000"

    },
]